// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.netty.study.example.sty010;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.netty.study.example.sty010.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_info = 1;</code>
   */
  String getResponseInfo();
  /**
   * <code>string response_info = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseInfoBytes();
}
